modLoader="javafml"
loaderVersion="[31.1,)"

license="All rights reserved"
[[mods]]
   modId="${mod_id}"
   version="${mod_version}"
   displayName="${mod_name}"
   displayURL="https://www.curseforge.com/minecraft/mc-mods/explosiont"
   credits="The MMD Discord Server is the best!"
   authors="Harmonised"
   description='''
   Explosions! ...Where..? What explosions?
   '''